# permissions for end users to edit customservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: customservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operators
    app.kubernetes.io/part-of: operators
    app.kubernetes.io/managed-by: kustomize
  name: customservice-editor-role
rules:
- apiGroups:
  - customapp.harshitdawar.com.harshitdawar.com
  resources:
  - customservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customapp.harshitdawar.com.harshitdawar.com
  resources:
  - customservices/status
  verbs:
  - get
